{'events_dash': {'browser_reload': 90,
                 'column_headers': 'pergroup',
                 'context': {'logtime': {'logtime_from': '8',
                                         'logtime_from_range': '3600',
                                         'logtime_until': '',
                                         'logtime_until_range': '3600'}},
                 'datasource': 'log_events',
                 'description': u'Events of the last 8 hours.\n',
                 'force_checkboxes': False,
                 'group_painters': [],
                 'hidden': True,
                 'hidebutton': False,
                 'icon': None,
                 'layout': 'table',
                 'linktitle': u'Events',
                 'mobile': False,
                 'mustsearch': False,
                 'name': 'events_dash',
                 'num_columns': 1,
                 'painters': [('log_icon', None, None),
                              ('log_time', None, None),
                              ('host', 'hostsvcevents', None),
                              ('service_description', 'svcevents', None),
                              ('log_plugin_output', None, None)],
                 'play_sounds': False,
                 'public': False,
                 'single_infos': [],
                 'sorters': [],
                 'title': u'Events of the last 4 hours (for the dashboard)',
                 'topic': 'Other',
                 'user_sortable': True}}
