[
  ('chrony', None, {}),
  ('cpu.loads', None, cpuload_default_levels),
  ('cpu.threads', None, threads_default_levels),
  ('df', u'/', {}),
  ('df', u'/data', {}),
  ('df', u'/home', {}),
  ('diskstat', u'SUMMARY', diskstat_default_levels),
  ('kernel', u'Context Switches', kernel_default_levels),
  ('kernel', u'Major Page Faults', kernel_default_levels),
  ('kernel', u'Process Creations', kernel_default_levels),
  ('kernel.util', None, {}),
  ('livestatus_status', u'prod', {}),
  ('lnx_if', u'2', {'state': ['1'], 'speed': 1000000000}),
  ('lnx_if', u'3', {'state': ['1'], 'speed': 1000000000}),
  ('logins', None, logins_default_levels),
  ('mem.linux', None, {}),
  ('mounts', u'/', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/data', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/home', [u'data=ordered', u'relatime', u'rw']),
  ('omd_apache', u'prod', None),
  ('omd_status', u'prod', None),
  ('postfix_mailq', None, {}),
  ('tcp_conn_stats', None, tcp_conn_stats_default_levels),
  ('uptime', None, {}),
]
