[
  ('chrony', None, {}),
  ('cpu.loads', None, cpuload_default_levels),
  ('cpu.threads', None, threads_default_levels),
  ('df', u'/', {}),
  ('df', u'/data', {}),
  ('df', u'/home', {}),
  ('diskstat', u'SUMMARY', diskstat_default_levels),
  ('ipmi', u'Summary', None),
  ('ipmi_sensors', u'Fan_Fan1', None),
  ('ipmi_sensors', u'Fan_Fan2', None),
  ('ipmi_sensors', u'Fan_Fan3', None),
  ('ipmi_sensors', u'Fan_Fan4', None),
  ('ipmi_sensors', u'Fan_Fan5', None),
  ('ipmi_sensors', u'Fan_Fan6', None),
  ('ipmi_sensors', u'Fan_Fan_Redundancy', None),
  ('ipmi_sensors', u'Temperature_Exhaust_Temp', None),
  ('ipmi_sensors', u'Temperature_Inlet_Temp', None),
  ('ipmi_sensors', u'Temperature_Temp', None),
  ('kernel', u'Context Switches', kernel_default_levels),
  ('kernel', u'Major Page Faults', kernel_default_levels),
  ('kernel', u'Process Creations', kernel_default_levels),
  ('kernel.util', None, {}),
  ('lnx_if', u'2', {'state': ['1'], 'speed': 1000000000}),
  ('local', u'HD_/tmp/fmq/SpolMonCtrl', None),
  ('local', u'HD_/tmp/fmq/moments/sband/shmem_20000', None),
  ('local', u'HD_/tmp/fmq/syscon', None),
  ('local', u'HD_/tmp/fmq/ts/sband/shmem_10000', None),
  ('local', u'HP_DataMapper_primary', None),
  ('local', u'HP_DsFileDist_suncal', None),
  ('local', u'HP_DsFileDist_time_series', None),
  ('local', u'HP_DsServerMgr_primary', None),
  ('local', u'HP_Fmq2Fmq_moments.sband', None),
  ('local', u'HP_Fmq2Fmq_moments.sband2', None),
  ('local', u'HP_Fmq2Fmq_ts.sband', None),
  ('local', u'HP_Fmq2Fmq_ts.sband2', None),
  ('local', u'HP_Iq2Dsr_sband', None),
  ('local', u'HP_Janitor_logs', None),
  ('local', u'HP_Janitor_time_series', None),
  ('local', u'HP_RadMon_log.sband', None),
  ('local', u'HP_Scout_primary', None),
  ('local', u'HP_SpolAngles2Fmq_s2d', None),
  ('local', u'HP_SpolSysconRelay_sband', None),
  ('local', u'HP_SpolTs2Fmq_sband', None),
  ('local', u'HP_SpolTsMonitor_sband', None),
  ('local', u'HP_SunCal_sband', None),
  ('local', u'HP_TsTcp2Fmq_rvp8', None),
  ('local', u'HawkSummary_Data', None),
  ('local', u'HawkSummary_Processes', None),
  ('local', u'SBandAntennaMovement_stationaryPeriod', None),
  ('logins', None, logins_default_levels),
  ('mem.linux', None, {}),
  ('mounts', u'/', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/data', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/home', [u'data=ordered', u'relatime', u'rw']),
  ('postfix_mailq', None, {}),
  ('tcp_conn_stats', None, tcp_conn_stats_default_levels),
  ('uptime', None, {}),
]
