[
  ('chrony', None, {}),
  ('cpu.loads', None, cpuload_default_levels),
  ('cpu.threads', None, threads_default_levels),
  ('df', u'/', {}),
  ('df', u'/data', {}),
  ('df', u'/home', {}),
  ('diskstat', u'SUMMARY', diskstat_default_levels),
  ('ipmi', u'Summary', None),
  ('ipmi_sensors', u'Fan_Fan1', None),
  ('ipmi_sensors', u'Fan_Fan2', None),
  ('ipmi_sensors', u'Fan_Fan3', None),
  ('ipmi_sensors', u'Fan_Fan4', None),
  ('ipmi_sensors', u'Fan_Fan5', None),
  ('ipmi_sensors', u'Fan_Fan6', None),
  ('ipmi_sensors', u'Fan_Fan_Redundancy', None),
  ('ipmi_sensors', u'Temperature_Exhaust_Temp', None),
  ('ipmi_sensors', u'Temperature_Inlet_Temp', None),
  ('ipmi_sensors', u'Temperature_Temp', None),
  ('kernel', u'Context Switches', kernel_default_levels),
  ('kernel', u'Major Page Faults', kernel_default_levels),
  ('kernel', u'Process Creations', kernel_default_levels),
  ('kernel.util', None, {}),
  ('lnx_if', u'2', {'state': ['1'], 'speed': 1000000000}),
  ('logins', None, logins_default_levels),
  ('mem.linux', None, {}),
  ('mounts', u'/', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/data', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/home', [u'data=ordered', u'relatime', u'rw']),
  ('postfix_mailq', None, {}),
  ('tcp_conn_stats', None, tcp_conn_stats_default_levels),
  ('uptime', None, {}),
]
