[
  ('chrony', None, {}),
  ('cpu.loads', None, cpuload_default_levels),
  ('cpu.threads', None, threads_default_levels),
  ('df', u'/', {}),
  ('df', u'/home', {}),
  ('df', u'/mnt/data', {}),
  ('diskstat', u'SUMMARY', diskstat_default_levels),
  ('ipmi', u'Summary', None),
  ('kernel', u'Context Switches', kernel_default_levels),
  ('kernel', u'Major Page Faults', kernel_default_levels),
  ('kernel', u'Process Creations', kernel_default_levels),
  ('kernel.util', None, {}),
  ('lnx_if', u'2', {'state': ['1'], 'speed': 1000000000}),
  ('local', u'HD_cfradial/moments/sband', None),
  ('local', u'HD_fmq/moments/sband/shmem_20000', None),
  ('local', u'HD_spdb/monitor/sband', None),
  ('local', u'HP_DataMapper_primary', None),
  ('local', u'HP_DsFileDist_front', None),
  ('local', u'HP_DsFmqServer_manager', None),
  ('local', u'HP_DsServerMgr_primary', None),
  ('local', u'HP_Dsr2Radx_covar.sband', None),
  ('local', u'HP_Dsr2Radx_moments.kband', None),
  ('local', u'HP_Dsr2Radx_moments.sband', None),
  ('local', u'HP_Dsr2Radx_moments.spoldrx', None),
  ('local', u'HP_Dsr2Radx_sunscan.sband', None),
  ('local', u'HP_RadxPartRain_sband.rhi', None),
  ('local', u'HP_RadxPartRain_sband.sur', None),
  ('local', u'HP_Rhi2Spdb_sband', None),
  ('local', u'HP_Scout_primary', None),
  ('local', u'HP_TsSmartSave_sband', None),
  ('local', u'HawkSummary_Data', None),
  ('local', u'HawkSummary_Processes', None),
  ('logins', None, logins_default_levels),
  ('mem.linux', None, {}),
  ('mounts', u'/', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/home', [u'data=ordered', u'relatime', u'rw']),
  ('mounts', u'/mnt/data', [u'attr2', u'inode64', u'noquota', u'relatime', u'rw']),
  ('postfix_mailq', None, {}),
  ('tcp_conn_stats', None, tcp_conn_stats_default_levels),
  ('uptime', None, {}),
]
